# Generated by Django 3.0.8 on 2020-07-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleCategory', models.CharField(choices=[('book', '도서'), ('event', '행사'), ('author', '저자')], max_length=255, verbose_name='기사카테고리')),
                ('articleTitle', models.CharField(max_length=255, verbose_name='기사제목')),
                ('articleExp', models.TextField(verbose_name='기사내용')),
                ('articleDate', models.DateField(auto_now_add=True, verbose_name='기사등록날짜')),
                ('eventName', models.CharField(max_length=255, null=True, verbose_name='행사이름')),
            ],
        ),
    ]
